name: Threat Feed Security Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # Run every Monday at 9 AM UTC

jobs:
  security-check:
    runs-on: ubuntu-latest
    name: Check for vulnerable packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run threat check
        uses: ./
        with:
          phylum_api_token: ${{ secrets.PHYLUM_API_TOKEN }}
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          debug: 'false'

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            summary.txt
            new-malicious-packages.txt
          retention-days: 30
